export const SHEET_USERS = 'USERS';
export const SHEET_SURAT_JALAN = 'SURAT_JALAN';
export const SHEET_DETAIL = 'DETAIL_SURAT_JALAN';
export const SHEET_JENIS_BARANG = 'REF_JENIS_BARANG';
export const SHEET_CABANG = 'REF_CABANG';
export const SHEET_ALAMAT = 'ALAMAT';
export const SHEET_PENERIMAAN_EXT = 'PENERIMAAN_SURAT_JALAN';
export const SHEET_DETAIL_PENERIMAAN_EXT = 'DETAIL_PENERIMAAN_SURAT_JALAN';

export const SESSION_TTL_MS = 1000 * 60 * 60 * 12; // 12 jam